# Load in NumPy

In [40]:
import numpy as np

### The Basis

In [46]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [42]:
b = np.array([[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]]


In [43]:
#Get Dimension
a.ndim

1

In [44]:
#Get Shape
b.shape

(2, 3)

In [47]:
#Get Type
a.dtype

dtype('int16')

In [48]:
#Get size
a.itemsize

2

In [51]:
#Get total size
print(a.size*a.itemsize)
print(a.nbytes)

6
6


In [52]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [53]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [54]:
#Get a specific element [r, c]
a[1, 5]

13

In [55]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [57]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [60]:
a[1, 5] = 20 ## single element
print(a)

a[:, 2] = [1, 2] ## entire row/column
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [61]:
#3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
#Get specific element (work outside in)
b[0,1,1]

4

In [63]:
#Replace
b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [64]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [67]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [68]:
#Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.31954005, 0.10404952],
       [0.51393556, 0.0591632 ],
       [0.73869357, 0.54674446],
       [0.06098163, 0.98945406]])

In [70]:
#Random Integer numbers
np.random.randint(-4, 8, size=(3,3))

array([[ 1, -1, -1],
       [-3,  2,  3],
       [ 3,  3,  3]])

In [71]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [73]:
#exercise
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [74]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [76]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [77]:
a + 2

array([3, 4, 5, 6])

In [78]:
a - 2

array([-1,  0,  1,  2])

In [79]:
a * 2

array([2, 4, 6, 8])

In [80]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [81]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [82]:
a ** 2

array([ 1,  4,  9, 16])

In [83]:
##Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [84]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [85]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [86]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [87]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [88]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.min(stats)

1

In [90]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [91]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [92]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
#Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Load Data from File

In [95]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [96]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])